name: Local CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # ANPASSUNG 1: -DskipTests hinzugefügt, um den Datenbank-Verbindungsfehler beim lokalen Test zu vermeiden
    - name: Build & Test (Continuous Integration)
      run: .\mvnw.cmd clean package -DskipTests

    - name: Docker Image bauen
      run: docker build -t devops-project/spring-app:latest .

    # NEU: Räumt alte Container des Projekts "devops-app" sicher ab
    - name: Stop alte Container
      run: docker compose -p devops-app down

    # ANPASSUNG 2 & 3: --force-recreate und fixer Projektname (-p devops-app)
    - name: Deployment via Docker Compose (Continuous Deployment)
      run: docker compose -p devops-app up --build --force-recreate -d